# cmake/embed_binary.cmake - turn a binary file into a .mm with a byte array the runtime can load.
#   cmake -DIN=file -DOUT=out.mm -DNAME=symbol -P embed_binary.cmake
file(READ "${IN}" bytes HEX)
string(REGEX MATCHALL "[0-9a-f][0-9a-f]" pairs "${bytes}")
string(REPLACE ";" ", 0x" body "${pairs}")
file(WRITE "${OUT}" "// generated by cmake/embed_binary.cmake from ${IN} - do not edit\n"
"static const unsigned char ${NAME}[] = { 0x${body} };\n"
"unsigned long strata_metallib_size = sizeof ${NAME};\n"
"const unsigned char* strata_metallib_data = ${NAME};\n")
