// src/platform/metal_runtime.mm - the Metal backend's runtime (docs/PORT_METAL/).
//
// Implements the CUDA-runtime surface declared in include/strata/metal_compat/cuda_runtime.h and the launcher
// builder in include/strata/platform/metal_launch.hpp.  The design constraints, all inherited from the engine's
// existing shape (see PLAN.md):
//
//   * unified memory: every cudaMalloc is a shared-storage MTLBuffer whose bytes the CPU can also touch, so a
//     cudaMemcpy is a plain memcpy - AFTER ordering it against the stream's pending work (commit + wait);
//   * a stream is a serial chain of command buffers on one queue; the current buffer stays open across
//     launches and is committed at the sync points (stream sync, event record, memcpy);
//   * capture is a TAPE: launches append (pipeline, buffers, bytes, geometry); cudaGraphLaunch re-encodes.
//     Replays stay correct because the engine already relies only on persistent buffers with changing
//     contents - the doorbells carry the dynamics (elementwise.hpp's ring/wait/publish);
//   * an event retains its command buffer and queries/waits on its completion. GPU end timestamps are
//     used for elapsed time when both exist, otherwise both endpoints use host record timestamps.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

#include "strata/platform/metal_launch.hpp"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

extern const unsigned char* strata_metallib_data;     // generated by cmake/embed_binary.cmake
extern unsigned long strata_metallib_size;

namespace strata::metal {
namespace {

id<MTLDevice> g_device;
id<MTLLibrary> g_library;
std::string g_code_error = "kernel library not loaded yet";
std::map<std::string, id<MTLComputePipelineState>> g_pso;
std::map<const void*, std::string> g_pso_names;      // pipeline -> kernel name, for the diagnostic profile

struct Range {
    const void* base;
    size_t bytes;
    id<MTLBuffer> buffer;
};
std::map<const void*, Range> g_ranges;                // keyed by base; lookups resolve interiors

struct TapeEntry {
    id<MTLComputePipelineState> pso = nil;
    MTLSize grid = {0, 0, 0}, block = {0, 0, 0};
    NSUInteger shared_bytes = 0;
    // a memcpy entry: pso == nil, the two buffers and the byte count (the engine's graphs carry memcpy nodes)
    bool is_copy = false;
    id<MTLBuffer> copy_dst = nil, copy_src = nil;
    NSUInteger copy_dst_off = 0, copy_src_off = 0, copy_bytes = 0;
    struct Arg {
        id<MTLBuffer> buffer = nil;                    // nil for a by-value arg (an uninitialised id is NOT nil)
        bool is_null = false;                          // a genuinely-null pointer argument (bound as nil)
        NSUInteger offset = 0, bytes = 0;
        std::vector<unsigned char> value;              // by-value payload (capture bakes it, as CUDA does)
    };
    std::vector<Arg> args;
};

struct Tape {
    std::vector<TapeEntry> entries;
};

struct Stream {
    id<MTLCommandQueue> queue = nil;
    id<MTLCommandBuffer> cur = nil;
    id<MTLComputeCommandEncoder> encoder = nil;
    id<MTLCommandBuffer> inflight = nil;   // the last COMMITTED cb, retained: query is NotReady until it completes
    dispatch_queue_t callbacks;                        // serial; runs event signals and host funcs in order
    Tape* capturing = nullptr;
    bool nonblocking = false;                         // excluded from synchronous legacy-stream copies
    // STRATA_METAL_KPROFILE, direct (uncaptured) launches: the open command buffer's sample buffer and the
    // kernel of each sampled pass, resolved when that command buffer completes
    id<MTLCounterSampleBuffer> kp_samples = nil;
    std::vector<std::string>* kp_names = nullptr;
    ~Stream() { if (capturing) delete capturing; }
};

struct Event {
    id<MTLCommandBuffer> buffer = nil;
    double at_ns = 0.0;
    ~Event() { [buffer release]; }
};

std::mutex g_mu;
std::vector<Stream*> g_streams;

double now_ns() {
    return std::chrono::duration<double, std::nano>(std::chrono::steady_clock::now().time_since_epoch()).count();
}

void boot() {
    @autoreleasepool {
        static std::once_flag once;
        std::call_once(once, [] {
            g_device = MTLCreateSystemDefaultDevice();
            if (g_device == nil) {
                g_code_error = "no Metal device on this Mac";
                return;
            }
            NSError* err = nil;
            void* bytes = std::malloc(strata_metallib_size);      // DISPATCH_DATA_DESTRUCTOR_DEFAULT frees it
            std::memcpy(bytes, strata_metallib_data, strata_metallib_size);
            dispatch_data_t data = dispatch_data_create(bytes, strata_metallib_size, NULL,
                                                        DISPATCH_DATA_DESTRUCTOR_DEFAULT);
            g_library = [g_device newLibraryWithData:data error:&err];
            dispatch_release(data);
            if (g_library == nil) {
                g_code_error = std::string("newLibraryWithData: ") +
                               (err ? err.localizedDescription.UTF8String : "unknown error");
                return;
            }
            g_code_error = "ok";
        });
    }
}

/// The engine's first CUDA call can be an allocation, not a device query: every entry point lands here.
void ensure_boot() { if (g_device == nil && g_code_error == "kernel library not loaded yet") boot(); }

id<MTLComputePipelineState> pso(const char* kernel) {
    std::lock_guard<std::mutex> lock(g_mu);
    ensure_boot();
    const std::string name(kernel);
    if (const auto it = g_pso.find(name); it != g_pso.end()) return it->second;
    NSError* err = nil;
    id<MTLFunction> f = [g_library newFunctionWithName:@(kernel)];
    if (f == nil) {
        std::fprintf(stderr, "strata-metal: no kernel named '%s' in the library\n", kernel);
        std::abort();
    }
    id<MTLComputePipelineState> p = [g_device newComputePipelineStateWithFunction:f error:&err];
    [f release];
    if (p == nil) {
        std::fprintf(stderr, "strata-metal: pipeline '%s': %s\n", kernel,
                     err ? err.localizedDescription.UTF8String : "unknown error");
        std::abort();
    }
    g_pso.emplace(name, p);
    g_pso_names.emplace((const void*) p, name);
    return p;
}

Stream* as_stream(cudaStream_t s) {
    if (s == nullptr) {                                 // the default stream: one implicit serial stream
        static Stream* def = nullptr;
        if (def == nullptr) {
            def = new Stream;
            def->queue = [g_device newCommandQueue];
            if (std::getenv("STRATA_METAL_DEBUG"))
                std::fprintf(stderr, "default stream created: device=%p queue=%p\n", (void*) g_device,
                             (void*) def->queue);
            def->callbacks = dispatch_queue_create("strata.default", DISPATCH_QUEUE_SERIAL);
            std::lock_guard<std::mutex> lock(g_mu);
            g_streams.push_back(def);
        }
        return def;
    }
    return (Stream*) s;
}

void end_compute(Stream* s) {
    if (s->encoder == nil) return;
    [s->encoder endEncoding];
    [s->encoder release];
    s->encoder = nil;
}

void attach_cb_timing(id<MTLCommandBuffer> cb);
bool cb_timing();

void kprofile_direct_attach(Stream* s);

void commit_current(Stream* s) {
    if (s->cur == nil) return;
    end_compute(s);
    if (cb_timing()) attach_cb_timing(s->cur);
    if (s->kp_samples != nil) kprofile_direct_attach(s);
    [s->cur commit];
    if (s->inflight != nil) [s->inflight release];
    s->inflight = s->cur;                               // the queue's own retain keeps it executable
    s->cur = nil;
}

id<MTLCommandBuffer> ensure_cb(Stream* s) {
    if (s->cur == nil) {
        s->cur = [s->queue commandBuffer];
        [s->cur retain];
    }
    return s->cur;
}

id<MTLComputeCommandEncoder> ensure_compute(Stream* s) {
    if (s->encoder == nil) {
        // A serial compute pass orders dependent dispatches without making one pass per kernel.
        s->encoder = [ensure_cb(s) computeCommandEncoder];
        [s->encoder retain];
    }
    return s->encoder;
}

void drain(Stream* s) {
    if (s->capturing != nullptr) return;
    commit_current(s);
    id<MTLCommandBuffer> cb = s->inflight;
    if (cb == nil) return;
    // An event may already have committed the work. Waiting only on cur then returns too early.
    [cb waitUntilCompleted];
    if (std::getenv("STRATA_METAL_DEBUG"))
        std::fprintf(stderr, "drain %p: cb=%p status=%ld err=%p\n", (void*) s, (void*) cb, (long) cb.status,
                     (void*) cb.error);
    if (cb.error != nil)
        std::fprintf(stderr, "strata-metal: command buffer failed: %s\n", cb.error.localizedDescription.UTF8String);
}

void sync_stream(Stream* s) {
    if (s->capturing) return;                           // a capture records; it does not execute
    commit_current(s);
}

bool resolve(const void* ptr, id<MTLBuffer>* buffer, NSUInteger* offset) {
    std::lock_guard<std::mutex> lock(g_mu);
    if (g_ranges.empty()) return false;
    auto it = g_ranges.upper_bound(ptr);
    if (it == g_ranges.begin()) return false;
    --it;
    const Range& r = it->second;
    const char* p = (const char*) ptr;
    if (p >= (const char*) r.base + r.bytes) return false;
    *buffer = r.buffer;
    *offset = NSUInteger(p - (const char*) r.base);
    return true;
}

/// Debug: the registry's contents (for STRATA_METAL_DEBUG traces). */
void dump_ranges(const char* why) {
    std::lock_guard<std::mutex> lock(g_mu);
    std::fprintf(stderr, "ranges (%s):", why);
    for (const auto& [base, r] : g_ranges)
        std::fprintf(stderr, " [%p..%p buf=%p]", base, (const char*) base + r.bytes, (void*) r.buffer);
    std::fprintf(stderr, "\n");
}

// read once: a token replays ~1,900 entries, and getenv walks the environment on every call
bool debug_trace() {
    static const bool on = std::getenv("STRATA_METAL_DEBUG") != nullptr;
    return on;
}
bool encoder_per_kernel() {
    static const bool on = std::getenv("STRATA_METAL_ENCODER_PER_KERNEL") != nullptr;
    return on;
}

void encode_entry(id<MTLComputeCommandEncoder> enc, const TapeEntry& e) {
    [enc setComputePipelineState:e.pso];
    int i = 0;
    if (debug_trace()) {
        std::fprintf(stderr, "  encode:");
        for (const TapeEntry::Arg& a : e.args)
            std::fprintf(stderr, a.buffer != nil ? " [%llu+%llu=%p]" : " [val%zu]",
                         (unsigned long long) a.buffer.length, (unsigned long long) a.offset,
                         a.buffer != nil ? a.buffer.contents : nullptr);
        std::fprintf(stderr, "\n");
    }
    for (const TapeEntry::Arg& a : e.args) {
        if (a.is_null) [enc setBuffer:nil offset:0 atIndex:i];
        else if (a.buffer != nil) [enc setBuffer:a.buffer offset:a.offset atIndex:i];
        else [enc setBytes:a.value.data() length:a.value.size() atIndex:i];
        ++i;
    }
    if (e.shared_bytes > 0) [enc setThreadgroupMemoryLength:e.shared_bytes atIndex:0];
    [enc dispatchThreadgroups:e.grid threadsPerThreadgroup:e.block];
}

bool compute_copies() {
    static const bool enabled = [] {
        const char* v = std::getenv("STRATA_METAL_COMPUTE_COPY");
        return !v || std::atoi(v) != 0;
    }();
    return enabled;
}

/// A memcpy as a REAL stream operation inside the stream's command buffer, so ordering and
/// hazard tracking are the GPU's, exactly like cudaMemcpyAsync on a CUDA stream.  This matters because a CPU
/// memcpy into a shared buffer is NOT guaranteed visible to a kernel that follows (measured: the M1 smoke's
/// reset case - the kernel read the line before the CPU's write had become GPU-visible; the blit path sees
/// the CPU's write because blit reads go through the same tracked buffer).
bool compute_copy_fits(NSUInteger bytes) { return compute_copies() && bytes <= 65536; }

void encode_compute_copy(id<MTLComputeCommandEncoder> enc, id<MTLBuffer> db, NSUInteger doff, id<MTLBuffer> sb,
                         NSUInteger soff, NSUInteger bytes) {
    const bool vector = ((doff | soff | bytes) & 15) == 0;
    const unsigned long n = bytes / (vector ? 16 : 1);
    const unsigned threads = n <= 32 ? 32 : 128;
    static id<MTLComputePipelineState> v16 = pso("runtime_copy16"), v1 = pso("runtime_copy1");
    [enc setComputePipelineState:vector ? v16 : v1];
    [enc setBuffer:db offset:doff atIndex:0];
    [enc setBuffer:sb offset:soff atIndex:1];
    [enc setBytes:&n length:sizeof(n) atIndex:2];
    [enc dispatchThreadgroups:MTLSizeMake((n + threads - 1) / threads, 1, 1)
          threadsPerThreadgroup:MTLSizeMake(threads, 1, 1)];
}

void encode_copy_on(Stream* s, id<MTLBuffer> db, NSUInteger doff, id<MTLBuffer> sb, NSUInteger soff,
                    NSUInteger bytes) {
    if (bytes == 0) return;
    // Avoid ending/restarting the serial compute pass for doorbells, scratch and state copies.
    // Large transfers still use the blit engine. Shared host sources remain live until stream flush.
    if (compute_copy_fits(bytes)) {
        encode_compute_copy(ensure_compute(s), db, doff, sb, soff, bytes);
        return;
    }
    end_compute(s);
    id<MTLBlitCommandEncoder> b = [ensure_cb(s) blitCommandEncoder];
    [b copyFromBuffer:sb sourceOffset:soff toBuffer:db destinationOffset:doff size:bytes];
    [b endEncoding];
}

// ---- diagnostics: order-preserving GPU timing ---------------------------------------------
// STRATA_METAL_CB_TIMING=1: each committed command buffer's GPU start/end, summed into a busy/span ratio on
// stderr (no encoding change). STRATA_METAL_KPROFILE=<csv>: every replayed tape entry gets its own compute (or
// blit) pass with stage-boundary timestamps (this GPU has no dispatch-boundary sampling). Both only attach to
// the command buffers the stream already builds: nothing is committed earlier, so the mapped-source late-write
// contract is untouched. Per-pass boundaries add GPU time; KPROFILE numbers are relative, not throughput.
// Timestamps are taken as nanoseconds: on the M2 Max sampleTimestamps advances GPU and CPU (ns) clocks equally.
bool cb_timing() {
    static const bool on = std::getenv("STRATA_METAL_CB_TIMING") != nullptr;
    return on;
}

struct CbTiming {
    std::mutex mu;
    double busy_s = 0, span_s = 0, first_start = 0, last_end = 0;
    unsigned long n = 0;
};
CbTiming g_cbt;

void attach_cb_timing(id<MTLCommandBuffer> cb) {
    [cb addCompletedHandler:^(id<MTLCommandBuffer> done) {
        const double a = done.GPUStartTime, b = done.GPUEndTime;
        if (a <= 0 || b <= a) return;
        std::lock_guard<std::mutex> lock(g_cbt.mu);
        if (g_cbt.n == 0) g_cbt.first_start = a;
        g_cbt.busy_s += b - a;
        g_cbt.last_end = b;
        if (++g_cbt.n % 256 == 0) {
            const double span = g_cbt.last_end - g_cbt.first_start;
            std::fprintf(stderr, "metal cb timing: %lu cbs, GPU busy %.1f ms of %.1f ms (%.1f%%), %.3f ms/cb\n",
                         g_cbt.n, g_cbt.busy_s * 1e3, span * 1e3, span > 0 ? 100.0 * g_cbt.busy_s / span : 0.0,
                         g_cbt.busy_s * 1e3 / (double) g_cbt.n);
            g_cbt.n = 0;
            g_cbt.busy_s = 0;
        }
    }];
}

const char* kprofile_path() {
    static const char* p = std::getenv("STRATA_METAL_KPROFILE");
    return p;
}

struct KStat {
    std::string name;
    MTLSize grid = {0, 0, 0}, block = {0, 0, 0};
    double sum_ns = 0, sq_ns = 0, gap_ns = 0;
    unsigned long n = 0;
};

struct KTape {
    std::vector<KStat> e;
    unsigned long launches = 0, measured = 0;
    double span_ns = 0, busy_ns = 0;
};

std::mutex g_kmu;
std::map<const void*, KTape> g_ktapes;

void kprofile_write() {   // caller holds g_kmu
    const std::string tmp = std::string(kprofile_path()) + ".tmp";
    std::FILE* f = std::fopen(tmp.c_str(), "w");
    if (f == nullptr) return;
    std::fprintf(f, "tape,entries,launches,entry,kernel,grid_x,grid_y,grid_z,threads,mean_us,sd_us,gap_us\n");
    for (const auto& [key, t] : g_ktapes) {
        for (size_t i = 0; i < t.e.size(); ++i) {
            const KStat& k = t.e[i];
            if (k.n == 0) continue;
            const double m = k.sum_ns / (double) k.n;
            const double v = std::max(0.0, k.sq_ns / (double) k.n - m * m);
            std::fprintf(f, "%p,%zu,%lu,%zu,%s,%llu,%llu,%llu,%llu,%.3f,%.3f,%.3f\n", key, t.e.size(), t.measured, i,
                         k.name.c_str(), (unsigned long long) k.grid.width, (unsigned long long) k.grid.height,
                         (unsigned long long) k.grid.depth,
                         (unsigned long long) (k.block.width * k.block.height * k.block.depth), m / 1e3,
                         std::sqrt(v) / 1e3, k.gap_ns / (double) k.n / 1e3);
        }
    }
    std::fclose(f);
    std::rename(tmp.c_str(), kprofile_path());
    for (const auto& [key, t] : g_ktapes)
        if (t.measured > 0)
            std::fprintf(stderr, "metal kprofile: tape %p entries=%zu measured=%lu span %.3f ms busy %.3f ms\n", key,
                         t.e.size(), t.measured, t.span_ns / (double) t.measured / 1e6,
                         t.busy_ns / (double) t.measured / 1e6);
}

// Direct launches (the prompt path is not captured): one sampled pass per launch in the open command buffer;
// per kernel name and grid, summed. A command buffer holds at most 2048 sampled passes - past that it is
// committed early (diagnostic only). Copies and MPS work are not sampled.
struct KDirect { double sum_ns = 0, gap_ns = 0; unsigned long n = 0; };
std::map<std::string, KDirect> g_kdirect;
unsigned long g_kdirect_cbs = 0;

void kprofile_direct_write() {   // caller holds g_kmu
    const std::string path = std::string(kprofile_path()) + ".direct.csv", tmp = path + ".tmp";
    std::FILE* f = std::fopen(tmp.c_str(), "w");
    if (f == nullptr) return;
    std::fprintf(f, "kernel_grid_threads,count,total_ms,mean_us,gap_before_us\n");
    for (const auto& [key, k] : g_kdirect)
        std::fprintf(f, "%s,%lu,%.3f,%.3f,%.3f\n", key.c_str(), k.n, k.sum_ns / 1e6, k.sum_ns / (double) k.n / 1e3,
                     k.gap_ns / (double) k.n / 1e3);
    std::fclose(f);
    std::rename(tmp.c_str(), path.c_str());
}

void kprofile_direct_attach(Stream* s) {
    id<MTLCounterSampleBuffer> sb = s->kp_samples;
    std::vector<std::string>* names = s->kp_names;
    s->kp_samples = nil;
    s->kp_names = nullptr;
    [s->cur addCompletedHandler:^(id<MTLCommandBuffer>) {
        const size_t n = names->size();
        NSData* data = n ? [sb resolveCounterRange:NSMakeRange(0, 2 * n)] : nil;
        if (data != nil && data.length >= 2 * n * sizeof(MTLCounterResultTimestamp)) {
            const MTLCounterResultTimestamp* r = (const MTLCounterResultTimestamp*) data.bytes;
            std::lock_guard<std::mutex> lock(g_kmu);
            for (size_t i = 0; i < n; ++i) {
                if (r[2 * i].timestamp == MTLCounterErrorValue || r[2 * i + 1].timestamp == MTLCounterErrorValue) continue;
                KDirect& k = g_kdirect[(*names)[i]];
                k.sum_ns += std::max(0.0, (double) r[2 * i + 1].timestamp - (double) r[2 * i].timestamp);
                if (i > 0 && r[2 * i - 1].timestamp != MTLCounterErrorValue)
                    k.gap_ns += std::max(0.0, (double) r[2 * i].timestamp - (double) r[2 * i - 1].timestamp);
                ++k.n;
            }
            if (++g_kdirect_cbs % 32 == 0) kprofile_direct_write();
        }
        [sb release];
        delete names;
    }];
}

/// One direct launch under STRATA_METAL_KPROFILE: its own sampled compute pass.
void kprofile_direct_encode(Stream* s, const TapeEntry& e, const char* name) {
    static id<MTLCounterSet> timestamps = [] {
        for (id<MTLCounterSet> cs in g_device.counterSets)
            if ([cs.name isEqualToString:MTLCommonCounterSetTimestamp]) return [cs retain];
        return (id<MTLCounterSet>) nil;
    }();
    constexpr size_t kCap = 2048;
    end_compute(s);
    if (s->kp_names != nullptr && s->kp_names->size() >= kCap) commit_current(s);
    id<MTLCommandBuffer> cb = ensure_cb(s);
    if (s->kp_samples == nil && timestamps != nil) {
        MTLCounterSampleBufferDescriptor* d = [[MTLCounterSampleBufferDescriptor new] autorelease];
        d.counterSet = timestamps;
        d.storageMode = MTLStorageModeShared;
        d.sampleCount = 2 * kCap;
        NSError* err = nil;
        s->kp_samples = [g_device newCounterSampleBufferWithDescriptor:d error:&err];
        s->kp_names = new std::vector<std::string>();
    }
    MTLComputePassDescriptor* pd = [MTLComputePassDescriptor computePassDescriptor];
    pd.dispatchType = MTLDispatchTypeSerial;
    if (s->kp_samples != nil) {
        const NSUInteger at = NSUInteger(2 * s->kp_names->size());
        pd.sampleBufferAttachments[0].sampleBuffer = s->kp_samples;
        pd.sampleBufferAttachments[0].startOfEncoderSampleIndex = at;
        pd.sampleBufferAttachments[0].endOfEncoderSampleIndex = at + 1;
        char key[256];
        std::snprintf(key, sizeof key, "%s %llux%llux%llu %llu", name, (unsigned long long) e.grid.width,
                      (unsigned long long) e.grid.height, (unsigned long long) e.grid.depth,
                      (unsigned long long) (e.block.width * e.block.height * e.block.depth));
        s->kp_names->push_back(key);
    }
    id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoderWithDescriptor:pd];
    encode_entry(enc, e);
    [enc endEncoding];
}

/// One profiled replay: each entry in its own sampled pass inside the stream's open command buffer.
void kprofile_launch(Stream* s, const void* key, const Tape& tape) {
    static const unsigned long skip = [] {
        const char* v = std::getenv("STRATA_METAL_KPROFILE_SKIP");
        return v ? std::strtoul(v, nullptr, 10) : 8ul;
    }();
    static id<MTLCounterSet> timestamps = [] {
        for (id<MTLCounterSet> cs in g_device.counterSets)
            if ([cs.name isEqualToString:MTLCommonCounterSetTimestamp]) return [cs retain];   // outlives the pool
        return (id<MTLCounterSet>) nil;
    }();
    const size_t n = tape.entries.size();
    bool measure = false;
    {
        std::lock_guard<std::mutex> lock(g_kmu);
        KTape& t = g_ktapes[key];
        if (t.e.size() != n) {
            t = KTape{};
            t.e.resize(n);
            for (size_t i = 0; i < n; ++i) {
                const TapeEntry& e = tape.entries[i];
                KStat& k = t.e[i];
                if (e.is_copy) {
                    k.name = compute_copy_fits(e.copy_bytes) ? "copy(compute)" : "copy(blit)";
                    k.grid = MTLSizeMake(e.copy_bytes, 1, 1);
                } else {
                    const auto it = g_pso_names.find((const void*) e.pso);
                    k.name = it != g_pso_names.end() ? it->second : "?";
                    k.grid = e.grid;
                    k.block = e.block;
                }
            }
        }
        measure = t.launches++ >= skip;
    }
    end_compute(s);
    id<MTLCommandBuffer> cb = ensure_cb(s);
    constexpr size_t kChunk = 2048;                      // 2 samples per entry; 4096 samples is the cap here
    std::vector<id<MTLCounterSampleBuffer>> bufs;
    for (size_t base = 0; base < n; base += kChunk) {
        id<MTLCounterSampleBuffer> sb = nil;
        if (measure && timestamps != nil) {
            MTLCounterSampleBufferDescriptor* d = [[MTLCounterSampleBufferDescriptor new] autorelease];
            d.counterSet = timestamps;
            d.storageMode = MTLStorageModeShared;
            d.sampleCount = 2 * std::min(kChunk, n - base);
            NSError* err = nil;
            sb = [g_device newCounterSampleBufferWithDescriptor:d error:&err];
        }
        if (sb == nil) measure = false;
        bufs.push_back(sb);
        for (size_t i = base; i < std::min(n, base + kChunk); ++i) {
            const TapeEntry& e = tape.entries[i];
            const NSUInteger at = NSUInteger(2 * (i - base));
            const bool blit = e.is_copy && !compute_copy_fits(e.copy_bytes);
            if (blit) {
                MTLBlitPassDescriptor* pd = [MTLBlitPassDescriptor blitPassDescriptor];
                if (sb != nil) {
                    pd.sampleBufferAttachments[0].sampleBuffer = sb;
                    pd.sampleBufferAttachments[0].startOfEncoderSampleIndex = at;
                    pd.sampleBufferAttachments[0].endOfEncoderSampleIndex = at + 1;
                }
                id<MTLBlitCommandEncoder> b = [cb blitCommandEncoderWithDescriptor:pd];
                if (e.copy_bytes > 0)
                    [b copyFromBuffer:e.copy_src sourceOffset:e.copy_src_off toBuffer:e.copy_dst
                        destinationOffset:e.copy_dst_off size:e.copy_bytes];
                [b endEncoding];
                continue;
            }
            MTLComputePassDescriptor* pd = [MTLComputePassDescriptor computePassDescriptor];
            pd.dispatchType = MTLDispatchTypeSerial;
            if (sb != nil) {
                pd.sampleBufferAttachments[0].sampleBuffer = sb;
                pd.sampleBufferAttachments[0].startOfEncoderSampleIndex = at;
                pd.sampleBufferAttachments[0].endOfEncoderSampleIndex = at + 1;
            }
            id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoderWithDescriptor:pd];
            if (e.is_copy) {
                if (e.copy_bytes > 0)
                    encode_compute_copy(enc, e.copy_dst, e.copy_dst_off, e.copy_src, e.copy_src_off, e.copy_bytes);
            } else {
                encode_entry(enc, e);
            }
            [enc endEncoding];
        }
    }
    if (!measure) {
        for (id<MTLCounterSampleBuffer> b : bufs) [b release];
        return;
    }
    [cb addCompletedHandler:^(id<MTLCommandBuffer>) {
        std::vector<double> t0(n, 0.0), t1(n, 0.0);
        bool ok = true;
        for (size_t c = 0; c < bufs.size(); ++c) {
            const size_t base = c * kChunk, m = std::min(kChunk, n - base);
            NSData* data = [bufs[c] resolveCounterRange:NSMakeRange(0, 2 * m)];
            if (data == nil || data.length < 2 * m * sizeof(MTLCounterResultTimestamp)) { ok = false; continue; }
            const MTLCounterResultTimestamp* r = (const MTLCounterResultTimestamp*) data.bytes;
            for (size_t i = 0; i < m; ++i) {
                if (r[2 * i].timestamp == MTLCounterErrorValue || r[2 * i + 1].timestamp == MTLCounterErrorValue)
                    ok = false;
                t0[base + i] = (double) r[2 * i].timestamp;
                t1[base + i] = (double) r[2 * i + 1].timestamp;
            }
        }
        for (id<MTLCounterSampleBuffer> b : bufs) [b release];
        if (!ok || n == 0) return;
        std::lock_guard<std::mutex> lock(g_kmu);
        KTape& t = g_ktapes[key];
        if (t.e.size() != n) return;
        double busy = 0;
        for (size_t i = 0; i < n; ++i) {
            const double d = std::max(0.0, t1[i] - t0[i]);
            KStat& k = t.e[i];
            k.sum_ns += d;
            k.sq_ns += d * d;
            k.gap_ns += i > 0 ? std::max(0.0, t0[i] - t1[i - 1]) : 0.0;
            ++k.n;
            busy += d;
        }
        t.busy_ns += busy;
        t.span_ns += std::max(0.0, t1[n - 1] - t0[0]);
        if (++t.measured % 16 == 0) kprofile_write();
    }];
}

}  // namespace

// ---- the launcher builder ---------------------------------------------------------------
struct Launch::Impl {
    const char* name;
    id<MTLComputePipelineState> pipeline;
    MTLSize grid, block;
    NSUInteger shared_bytes;
    Stream* stream;
    TapeEntry entry;                                   // filled by buf()/scalar(); encoded at done()
};

Launch::Launch(const char* kernel, unsigned gx, unsigned gy, unsigned gz, unsigned bx, unsigned by, unsigned bz,
               size_t shared_bytes, void* stream)
    : impl_(new Impl) {
    impl_->name = kernel;
    impl_->pipeline = pso(kernel);
    [impl_->pipeline retain];
    impl_->grid = MTLSizeMake(gx, gy, gz);
    impl_->block = MTLSizeMake(bx, by, bz);
    impl_->shared_bytes = NSUInteger(shared_bytes);
    impl_->stream = as_stream((cudaStream_t) stream);
    impl_->entry.pso = impl_->pipeline;                // Impl owns one retain; the entry shares it
    impl_->entry.grid = impl_->grid;
    impl_->entry.block = impl_->block;
    impl_->entry.shared_bytes = NSUInteger(shared_bytes);
}

Launch::~Launch() {
    [impl_->pipeline release];
    delete impl_;
}

Launch& Launch::buf(const void* ptr) {
    TapeEntry::Arg a;
    if (ptr == nullptr) {                               // CUDA kernels test their pointers: pass null
        a.is_null = true;                               // through as a null binding, not a dummy buffer
        impl_->entry.args.push_back(std::move(a));
        return *this;
    }
    id<MTLBuffer> buffer = nil;
    NSUInteger offset = 0;
    if (!resolve(ptr, &buffer, &offset)) {
        std::fprintf(stderr, "strata-metal: launch argument %p is not a runtime buffer\n", ptr);
        std::abort();
    }
    a.buffer = buffer;
    a.offset = offset;
    impl_->entry.args.push_back(std::move(a));
    return *this;
}

Launch& Launch::scalar(const void* p, size_t bytes) {
    TapeEntry::Arg a;
    a.bytes = NSUInteger(bytes);
    a.value.assign((const unsigned char*) p, (const unsigned char*) p + bytes);
    impl_->entry.args.push_back(std::move(a));
    return *this;
}

void Launch::done() {
    @autoreleasepool {
    Stream* s = impl_->stream;
    // RULE 10 (measured, gdn's port): a dispatch wider than the pipeline's occupancy limit is SILENTLY
    // DROPPED on this GPU - the command buffer completes clean and nothing runs (a register-heavy kernel
    // pinned to 384 threads took a 512-thread launch and wrote nothing, no error anywhere).  Refuse it
    // here, while the mistake still names its kernel.
    if (impl_->block.width * impl_->block.height * impl_->block.depth >
        impl_->pipeline.maxTotalThreadsPerThreadgroup) {
        std::fprintf(stderr, "strata-metal: launch of '%s' wants %llu threads but its pipeline allows %zu - "
                             "the dispatch would be dropped silently\n",
                     impl_->name, (unsigned long long) impl_->block.width,
                     (std::size_t) impl_->pipeline.maxTotalThreadsPerThreadgroup);
        std::abort();
    }
    if (s->capturing != nullptr) {
        s->capturing->entries.push_back(std::move(impl_->entry));
        return;
    }
    if (kprofile_path() != nullptr) {      // diagnostic: a sampled pass per launch (see kprofile_direct_encode)
        kprofile_direct_encode(s, impl_->entry, impl_->name);
        return;
    }
    id<MTLCommandBuffer> cb = ensure_cb(s);
    id<MTLComputeCommandEncoder> enc = cb != nil ? ensure_compute(s) : nil;
    if (debug_trace()) {
        std::fprintf(stderr, "done: %s stream=%p cb=%p enc=%p args:", impl_->name, (void*) s, (void*) cb,
                     (void*) enc);
        for (const auto& a : impl_->entry.args)
            std::fprintf(stderr, a.buffer != nil ? " buf%llu@%llu" : " val%zu",
                         a.buffer != nil ? (unsigned long long) a.buffer.length
                                         : (unsigned long long) a.offset,
                         a.buffer != nil ? (unsigned long long) a.offset : 0ull);
        std::fprintf(stderr, "\n");
    }
    if (enc == nil) return;
    encode_entry(enc, impl_->entry);
    if (encoder_per_kernel()) end_compute(s);
    if (debug_trace()) {
        std::fprintf(stderr, "launch: grid=%llu block=%llu args=%zu:",
                     (unsigned long long) impl_->entry.grid.width,
                     (unsigned long long) impl_->entry.block.width, impl_->entry.args.size());
        for (const auto& a : impl_->entry.args)
            std::fprintf(stderr, a.buffer != nil ? " buf+%zu" : " val%zu", a.buffer != nil ? a.offset : a.value.size());
        std::fprintf(stderr, "\n");
    }
    }
}

const char* code_state() { return g_code_error.c_str(); }

// ---- the MPS seam (M4, the prefill GEMM) - declared in metal_launch.hpp -------------------
// MPS encodes its own kernels; the three helpers below hand a ported .mm the same facts Launch uses
// internally, as opaque pointers so the header stays includable from plain C++.
void* mtl_command_buffer(void* stream) {
    ensure_boot();
    Stream* s = as_stream((cudaStream_t) stream);
    end_compute(s);                           // MPS opens its own encoders on this command buffer
    id<MTLCommandBuffer> cb = ensure_cb(s);      // the SAME open buffer Launch encodes into
    [cb retain];                                 // the caller releases it after encoding
    return (__bridge void*) cb;
}

bool resolve_buffer(const void* ptr, void** buffer, uint64_t* offset) {
    ensure_boot();
    id<MTLBuffer> b = nil;
    NSUInteger off = 0;
    if (!resolve(ptr, &b, &off) || b == nil) return false;
    [b retain];                                  // the caller releases it after encoding
    *buffer = (__bridge void*) b;
    *offset = (uint64_t) off;
    return true;
}

void* mtl_device() {
    ensure_boot();
    return (__bridge void*) g_device;            // borrowed: boot() retains it for the process
}

void poison(float* p, uint64_t n_floats) {
    // the same chunking device.cu uses for the CUDA kernel (gridDim.x is 32-bit there)
    const unsigned threads = 256;
    const uint64_t blocks = (n_floats + threads - 1) / threads;
    const uint64_t max_blocks = 0x7FFFFFFFull;
    for (uint64_t b = 0; b < blocks; b += max_blocks) {
        const uint64_t chunk = (blocks - b < max_blocks) ? blocks - b : max_blocks;
        Launch k("poison_kernel", (unsigned) chunk, 1, 1, threads, 1, 1, 0, nullptr);
        k.buf(p + b * threads);
        k.done();
    }
    cudaDeviceSynchronize();
}

}  // namespace strata::metal

// ---- the CUDA runtime surface ----------------------------------------------------------
using strata::metal::Event;
using strata::metal::Stream;
using strata::metal::Tape;
using strata::metal::ensure_boot;
using strata::metal::commit_current;
using strata::metal::drain;
using strata::metal::encode_copy_on;
using strata::metal::resolve;
using strata::metal::ensure_cb;
using strata::metal::g_device;
using strata::metal::g_mu;
using strata::metal::g_ranges;
using strata::metal::g_streams;
using strata::metal::now_ns;

static thread_local cudaError_t t_last_error = cudaSuccess;

static cudaError_t fail(cudaError_t e) { t_last_error = e; return e; }

extern "C" {

const char* cudaGetErrorString(cudaError_t e) {
    switch (e) {
        case cudaSuccess: return "no error";
        case cudaErrorInvalidValue: return "invalid argument";
        case cudaErrorMemoryAllocation: return "out of memory";
        case cudaErrorNotReady: return "not ready";
        case cudaErrorStreamCaptureUnsupported: return "operation not permitted during stream capture";
        default: return "unknown Metal-runtime error";
    }
}

cudaError_t cudaGetLastError(void) { const cudaError_t e = t_last_error; t_last_error = cudaSuccess; return e; }
cudaError_t cudaPeekAtLastError(void) { return t_last_error; }

cudaError_t cudaGetDeviceCount(int* count) {
    ensure_boot();
    if (g_device == nil && strata::metal::g_code_error == "kernel library not loaded yet") strata::metal::boot();
    *count = (g_device != nil) ? 1 : 0;
    return cudaSuccess;
}

cudaError_t cudaSetDevice(int ordinal) {
    ensure_boot(); return ordinal == 0 ? cudaSuccess : fail(cudaErrorInvalidValue); }
cudaError_t cudaGetDevice(int* ordinal) { *ordinal = 0; return cudaSuccess; }
cudaError_t cudaInitDevice(int ordinal, unsigned, int) { return cudaSetDevice(ordinal); }

cudaError_t cudaGetDeviceProperties(cudaDeviceProp* p, int ordinal) {
    ensure_boot();
    if (ordinal != 0 || g_device == nil) return fail(cudaErrorInvalidValue);
    std::memset(p, 0, sizeof *p);
    std::snprintf(p->name, sizeof p->name, "%s", g_device.name.UTF8String);
    p->totalGlobalMem = (size_t) g_device.recommendedMaxWorkingSetSize;
    p->sharedMemPerBlock = (size_t) g_device.maxThreadgroupMemoryLength;
    p->warpSize = 32;                                  // one simdgroup
    p->major = 10; p->minor = 0;                       // "Metal Apple family": the cc gate sees 10.0 >= 7.5
    p->maxThreadsPerBlock = (int) g_device.maxThreadsPerThreadgroup.width;
    p->multiProcessorCount = (int) g_device.registryID;    // a stable per-GPU id, for logs only
    return cudaSuccess;
}

cudaError_t cudaDeviceGetAttribute(int* value, int attr, int) {
    ensure_boot();
    if (g_device == nil) return fail(cudaErrorInvalidValue);
    switch (attr) {
        case cudaDevAttrMaxSharedMemoryPerBlock:
        case cudaDevAttrMaxSharedMemoryPerBlockOptin:
            *value = (int) g_device.maxThreadgroupMemoryLength; return cudaSuccess;
        case cudaDevAttrComputeCapabilityMajor: *value = 10; return cudaSuccess;
        case cudaDevAttrComputeCapabilityMinor: *value = 0; return cudaSuccess;
        case cudaDevAttrClockRate: *value = 0; return cudaSuccess;
        case cudaDevAttrMultiProcessorCount: *value = 1; return cudaSuccess;   // not a Metal concept
        default: return fail(cudaErrorInvalidValue);
    }
}

cudaError_t cudaDeviceSynchronize(void) {
    ensure_boot();
    std::vector<Stream*> streams;
    { std::lock_guard<std::mutex> lock(g_mu); streams = g_streams; }
    for (Stream* s : streams) if (!s->capturing) commit_current(s);
    for (Stream* s : streams) drain(s);
    return cudaSuccess;
}

cudaError_t cudaMemGetInfo(size_t* free_bytes, size_t* total_bytes) {
    ensure_boot();
    if (g_device == nil) return fail(cudaErrorInvalidValue);
    *total_bytes = (size_t) g_device.recommendedMaxWorkingSetSize;        // the GPU's working-set budget
    *free_bytes = *total_bytes > g_device.currentAllocatedSize
                      ? *total_bytes - (size_t) g_device.currentAllocatedSize : 0;
    return cudaSuccess;
}

cudaError_t cudaDriverGetVersion(int* v) { *v = 0; return cudaSuccess; }
cudaError_t cudaRuntimeGetVersion(int* v) { *v = 0; return cudaSuccess; }

// ---- memory ----
cudaError_t cudaMalloc(void** ptr, size_t bytes) {
    ensure_boot();
    if (bytes == 0) { *ptr = nullptr; return cudaSuccess; }
    @autoreleasepool {
        id<MTLBuffer> b = [g_device newBufferWithLength:bytes options:MTLResourceStorageModeShared];
        if (b == nil) return fail(cudaErrorMemoryAllocation);
        std::lock_guard<std::mutex> lock(g_mu);
        g_ranges[b.contents] = { b.contents, bytes, b };
        *ptr = b.contents;
    }
    return cudaSuccess;
}

cudaError_t cudaFree(void* ptr) {
    if (ptr == nullptr) return cudaSuccess;
    std::lock_guard<std::mutex> lock(g_mu);
    const auto it = g_ranges.find(ptr);
    if (it == g_ranges.end()) return fail(cudaErrorInvalidValue);
    if (it->second.buffer != nil) [it->second.buffer release];
    g_ranges.erase(it);
    return cudaSuccess;
}

static cudaError_t host_alloc(void** ptr, size_t bytes, bool page_align) {
    ensure_boot();
    (void) page_align;
    const size_t allocated = ((std::max(bytes, size_t(1)) + 16383) / 16384) * 16384;
    void* p = std::aligned_alloc(16384, allocated);
    if (p == nullptr) return fail(cudaErrorMemoryAllocation);
    std::memset(p, 0, bytes);
    @autoreleasepool {
        id<MTLBuffer> b = [g_device newBufferWithBytesNoCopy:p length:allocated
                                                    options:MTLResourceStorageModeShared deallocator:nil];
        if (b == nil) {                                 // still usable as host memory; the GPU just cannot see it
            std::fprintf(stderr, "strata-metal: cudaHostAlloc: no-copy wrap failed (%zu B)\n", bytes);
        }
        std::lock_guard<std::mutex> lock(g_mu);
        g_ranges[p] = { p, bytes, b };
    }
    *ptr = p;
    return cudaSuccess;
}

cudaError_t cudaMallocHost(void** ptr, size_t bytes) { return host_alloc(ptr, bytes, false); }
cudaError_t cudaHostAlloc(void** ptr, size_t bytes, unsigned) { return host_alloc(ptr, bytes, true); }

cudaError_t cudaFreeHost(void* ptr) {
    if (ptr == nullptr) return cudaSuccess;
    std::lock_guard<std::mutex> lock(g_mu);
    const auto it = g_ranges.find(ptr);
    const bool known = it != g_ranges.end();
    if (known) {
        if (it->second.buffer != nil) [it->second.buffer release];
        g_ranges.erase(it);
    }
    std::free(ptr);                                    // the MTLBuffer wraps it no-copy; nothing else to free
    return known ? cudaSuccess : fail(cudaErrorInvalidValue);
}

cudaError_t cudaHostRegister(void* ptr, size_t bytes, unsigned) {
    ensure_boot();
    // page-aligned no-copy wrap; a non-page-aligned arena is refused (pinned.cu's fallback paths handle it)
    if (((uintptr_t) ptr % 16384) != 0 || (bytes % 64) != 0) return fail(cudaErrorInvalidValue);
    @autoreleasepool {
        id<MTLBuffer> b = [g_device newBufferWithBytesNoCopy:ptr length:bytes
                                                    options:MTLResourceStorageModeShared deallocator:nil];
        if (b == nil) return fail(cudaErrorInvalidValue);
        std::lock_guard<std::mutex> lock(g_mu);
        g_ranges[ptr] = { ptr, bytes, b };
    }
    return cudaSuccess;
}

cudaError_t cudaHostUnregister(void* ptr) {
    std::lock_guard<std::mutex> lock(g_mu);
    const auto it = g_ranges.find(ptr);
    if (it != g_ranges.end()) {
        if (it->second.buffer != nil) [it->second.buffer release];
        g_ranges.erase(it);                            // the host memory itself stays (it was the caller's)
    }
    return cudaSuccess;
}

cudaError_t cudaHostGetDevicePointer(void** device_ptr, const void* host_ptr, unsigned) {
    *device_ptr = const_cast<void*>(host_ptr);         // unified memory: the same address
    return cudaSuccess;
}

// A copy between runtime buffers runs on the stream as a blit (ordered, hazard-tracked).  A host pointer the
// runtime does not know (a test fixture's std::vector, a stack array) falls back to drain-then-memcpy, which
// is safe for the same stream and is all such callers need.
static cudaError_t copy_on_stream(void* dst, const void* src, size_t bytes, cudaStream_t stream, bool sync) {
    ensure_boot();
    Stream* s = strata::metal::as_stream(stream);
    @autoreleasepool {
        id<MTLBuffer> db = nil, sb = nil;
        NSUInteger doff = 0, soff = 0;
        bool dst_known = strata::metal::resolve(dst, &db, &doff);
        bool src_known = strata::metal::resolve(src, &sb, &soff);
        bool staged = false;
        if (dst_known && db != nil && !src_known) {
            // H2D from memory the runtime does not own (a test fixture's vector): stage it into a buffer the
            // GPU reads through a blit - a bare CPU memcpy is NOT guaranteed GPU-visible (measured, M1)
            if (std::getenv("STRATA_METAL_DEBUG")) {
                std::fprintf(stderr, "staging H2D %zu B from %p\n", bytes, src);
                strata::metal::dump_ranges("before staging");
            }
            sb = [g_device newBufferWithBytes:src length:bytes options:MTLResourceStorageModeShared];
            if (sb == nil) return fail(cudaErrorMemoryAllocation);
            staged = true;
            if (std::getenv("STRATA_METAL_DEBUG")) std::fprintf(stderr, "  staged -> %p\n", (void*) sb);
            soff = 0;
            src_known = true;
        }
        if (std::getenv("STRATA_METAL_DEBUG"))
            std::fprintf(stderr, "copy %p <- %p %zu B: dst_known=%d src_known=%d\n", dst, src, bytes,
                         (int) dst_known, (int) src_known);
        if (dst_known && src_known && db != nil && sb != nil) {
            if (s->capturing != nullptr) {
                strata::metal::TapeEntry e;
                e.is_copy = true;
                [db retain]; [sb retain];
                e.copy_dst = db; e.copy_dst_off = doff;
                e.copy_src = sb; e.copy_src_off = soff;
                e.copy_bytes = NSUInteger(bytes);
                s->capturing->entries.push_back(std::move(e));
                if (staged) [sb release];
                return cudaSuccess;                   // a captured async copy runs at replay
            }
            encode_copy_on(s, db, doff, sb, soff, NSUInteger(bytes));
            if (staged) [sb release];  // the command buffer retains the encoded resource
            if (sync) drain(s);
            return cudaSuccess;
        }
        // D2H into unowned memory: the source's GPU work is drained first, then the CPU reads (visible)
        drain(s);
        std::memcpy(dst, src, bytes);
        return cudaSuccess;
    }
}

cudaError_t cudaMemcpy(void* dst, const void* src, size_t bytes, cudaMemcpyKind) {
    // A synchronous legacy-stream copy observes previous work on blocking streams. Keeping this
    // ordering here lets data-producing kernels stay asynchronous instead of each forcing a wait.
    ensure_boot();
    std::vector<Stream*> streams;
    { std::lock_guard<std::mutex> lock(g_mu); streams = g_streams; }
    for (Stream* s : streams) if (!s->nonblocking && !s->capturing) commit_current(s);
    for (Stream* s : streams) if (!s->nonblocking && !s->capturing) drain(s);
    return copy_on_stream(dst, src, bytes, nullptr, true);
}

cudaError_t cudaMemcpyAsync(void* dst, const void* src, size_t bytes, cudaMemcpyKind, cudaStream_t stream) {
    return copy_on_stream(dst, src, bytes, stream, false);
}

cudaError_t cudaMemcpy2DAsync(void* dst, size_t dpitch, const void* src, size_t spitch,
                            size_t width, size_t count, cudaMemcpyKind kind, cudaStream_t stream) {
    if (width == 0 || count == 0) return cudaSuccess;
    if (width > dpitch || width > spitch) return fail(cudaErrorInvalidValue);
    ensure_boot();
    id<MTLBuffer> db = nil, sb = nil;
    NSUInteger doff = 0, soff = 0;
    if (strata::metal::compute_copies() && strata::metal::resolve(dst, &db, &doff) && db != nil &&
        strata::metal::resolve(src, &sb, &soff) && sb != nil) {
        const bool vector = ((doff | soff | dpitch | spitch | width) & 15) == 0;
        const unsigned long unit = vector ? 16 : 1, w = width / unit;
        const unsigned long dp = dpitch / unit, sp = spitch / unit;
        const unsigned threads = w <= 32 ? 32 : 128;
        strata::metal::Launch k(vector ? "runtime_copy2d16" : "runtime_copy2d1",
                               (unsigned) ((w + threads - 1) / threads), (unsigned) count, 1,
                               threads, 1, 1, 0, stream);
        k.buf(dst).buf(src).scalar(dp).scalar(sp).scalar(w); k.done();
        return cudaSuccess;
    }
    // Unregistered host memory keeps the staging/drain semantics of the one-dimensional API.
    for (size_t row = 0; row < count; ++row) {
        const auto e = copy_on_stream((char*) dst + row * dpitch, (const char*) src + row * spitch,
                                      width, stream, false);
        if (e != cudaSuccess) return e;
    }
    return cudaSuccess;
}

cudaError_t cudaMemset(void* ptr, int value, size_t bytes) {
    return cudaMemsetAsync(ptr, value, bytes, nullptr), drain(strata::metal::as_stream(nullptr)), cudaSuccess;
}

cudaError_t cudaMemsetAsync(void* ptr, int value, size_t bytes, cudaStream_t stream) {
    ensure_boot();
    Stream* s = strata::metal::as_stream(stream);
    id<MTLBuffer> b = nil;
    NSUInteger off = 0;
    if (strata::metal::resolve(ptr, &b, &off) && b != nil && s->capturing == nullptr) {
        strata::metal::Launch k("memset8_kernel", (unsigned) ((bytes + 255) / 256), 1, 1, 256, 1, 1, 0, (void*) s);
        k.buf(ptr);
        const unsigned char v = (unsigned char) value;
        const unsigned long n = (unsigned long) bytes;
        k.scalar(v).scalar(n);
        k.done();
        return cudaSuccess;
    }
    drain(s);
    std::memset(ptr, value, bytes);
    return cudaSuccess;
}

cudaError_t cudaMemcpyToSymbol(const void*, const void*, size_t, size_t, cudaMemcpyKind) {
    return fail(cudaErrorInvalidValue);                // s2_gemv_fast's constant tables: not ported yet
}

// ---- functions ----
cudaError_t cudaFuncGetAttributes(cudaFuncAttributes* attr, const void*) {
    std::memset(attr, 0, sizeof *attr);
    attr->maxThreadsPerBlock = 1024;
    attr->sharedSizeBytes = 0;
    return cudaSuccess;
}

cudaError_t cudaFuncSetAttribute(const void*, int, int) { return cudaSuccess; }
cudaError_t cudaFuncGetName(const char** name, const void* func) { *name = (const char*) func; return cudaSuccess; }

// ---- streams & events ----
cudaError_t cudaStreamCreate(cudaStream_t* stream) { return cudaStreamCreateWithFlags(stream, 0); }

cudaError_t cudaStreamCreateWithFlags(cudaStream_t* stream, unsigned flags) {
    ensure_boot();
    if (g_device == nil) return fail(cudaErrorInvalidValue);
    Stream* s = new Stream;
    s->nonblocking = (flags & cudaStreamNonBlocking) != 0;
    s->queue = [g_device newCommandQueue];
    s->callbacks = dispatch_queue_create("strata.stream", DISPATCH_QUEUE_SERIAL);
    std::lock_guard<std::mutex> lock(g_mu);
    g_streams.push_back(s);
    *stream = s;
    return cudaSuccess;
}

cudaError_t cudaStreamDestroy(cudaStream_t stream) {
    Stream* s = strata::metal::as_stream(stream);
    drain(s);
    dispatch_sync(s->callbacks, ^{});
    [s->inflight release];
    [s->queue release];
    dispatch_release(s->callbacks);
    std::lock_guard<std::mutex> lock(g_mu);
    g_streams.erase(std::remove(g_streams.begin(), g_streams.end(), s), g_streams.end());
    delete s;
    return cudaSuccess;
}

cudaError_t cudaStreamSynchronize(cudaStream_t stream) {
    ensure_boot();
    Stream* s = strata::metal::as_stream(stream);
    if (s->capturing) return cudaSuccess;
    strata::metal::drain(s);
    return cudaSuccess;
}

cudaError_t cudaStreamQuery(cudaStream_t stream) {
    Stream* s = strata::metal::as_stream(stream);
    if (s->cur != nil) return cudaErrorNotReady;
    if (s->inflight != nil) {
        // M6's first real token run caught the lie: a query right after a commit said "finished" while the
        // GPU was still executing and the engine read a ring that had not run - NotReady until it completes
        if ([s->inflight status] < MTLCommandBufferStatusCompleted) return cudaErrorNotReady;
        [s->inflight release];
        s->inflight = nil;
    }
    return cudaSuccess;
}

cudaError_t cudaStreamWaitEvent(cudaStream_t stream, cudaEvent_t event, unsigned) {
    Event* e = (Event*) event;
    [e->buffer waitUntilCompleted];
    (void) stream;
    return cudaSuccess;
}

cudaError_t cudaStreamIsCapturing(cudaStream_t stream, cudaStreamCaptureStatus* status) {
    Stream* s = strata::metal::as_stream(stream);
    *status = s->capturing ? cudaStreamCaptureStatusActive : cudaStreamCaptureStatusNone;
    return cudaSuccess;
}

cudaError_t cudaEventCreate(cudaEvent_t* event) { return cudaEventCreateWithFlags(event, 0); }

cudaError_t cudaEventCreateWithFlags(cudaEvent_t* event, unsigned) {
    *event = new Event;
    return cudaSuccess;
}

cudaError_t cudaEventDestroy(cudaEvent_t event) {
    delete (Event*) event;
    return cudaSuccess;
}

cudaError_t cudaEventRecord(cudaEvent_t event, cudaStream_t stream) {
    ensure_boot();
    Stream* s = strata::metal::as_stream(stream);
    Event* e = (Event*) event;
    if (s->capturing) return cudaSuccess;              // an event inside a capture: the replay below rings it
    commit_current(s);
    [s->inflight retain];
    [e->buffer release];
    e->buffer = s->inflight;
    e->at_ns = now_ns();
    return cudaSuccess;
}

cudaError_t cudaEventQuery(cudaEvent_t event) {
    Event* e = (Event*) event;
    // Query the driver, not a callback-thread flag: this also makes shared-buffer writes visible.
    return e->buffer == nil || e->buffer.status >= MTLCommandBufferStatusCompleted
        ? cudaSuccess : cudaErrorNotReady;
}

cudaError_t cudaEventSynchronize(cudaEvent_t event) {
    Event* e = (Event*) event;
    [e->buffer waitUntilCompleted];
    return cudaSuccess;
}

cudaError_t cudaEventElapsedTime(float* ms, cudaEvent_t start, cudaEvent_t end) {
    Event* a = (Event*) start, * b = (Event*) end;
    if (cudaEventQuery(start) != cudaSuccess || cudaEventQuery(end) != cudaSuccess) return cudaErrorNotReady;
    const double ag = a->buffer.GPUEndTime, bg = b->buffer.GPUEndTime;
    // Empty streams have no GPU timestamp. Never subtract timestamps from different clocks.
    *ms = ag > 0 && bg > 0 ? float((bg - ag) * 1e3) : float((double(b->at_ns) - double(a->at_ns)) / 1e6);
    return cudaSuccess;
}

cudaError_t cudaLaunchHostFunc(cudaStream_t stream, void (*fn)(void*), void* user) {
    Stream* s = strata::metal::as_stream(stream);
    if (s->capturing) return fail(cudaErrorStreamCaptureUnsupported);
    ensure_cb(s);
    commit_current(s);
    id<MTLCommandBuffer> cb = s->inflight;
    dispatch_async(s->callbacks, ^{
        [cb waitUntilCompleted];
        fn(user);
    });
    return cudaSuccess;
}

// ---- graphs: the tape --------------------------------------------------------------------
cudaError_t cudaStreamBeginCapture(cudaStream_t stream, int) {
    Stream* s = strata::metal::as_stream(stream);
    if (s->capturing) return fail(cudaErrorStreamCaptureUnsupported);
    commit_current(s);
    s->capturing = new Tape;
    return cudaSuccess;
}

cudaError_t cudaStreamEndCapture(cudaStream_t stream, cudaGraph_t* graph) {
    Stream* s = strata::metal::as_stream(stream);
    if (s->capturing == nullptr) { *graph = nullptr; return fail(cudaErrorStreamCaptureUnsupported); }
    *graph = s->capturing;
    s->capturing = nullptr;
    return cudaSuccess;
}

cudaError_t cudaGraphInstantiate(cudaGraphExec_t* exec, cudaGraph_t graph, void*, void*, unsigned long long) {
    // CUDA permits destroying the source graph immediately after instantiation (MTP does so).
    Tape* copy = new Tape(*(Tape*) graph);
    for (const auto& e : copy->entries)
        if (e.is_copy) { [e.copy_dst retain]; [e.copy_src retain]; }
    *exec = copy;
    return cudaSuccess;
}

cudaError_t cudaGraphLaunch(cudaGraphExec_t exec, cudaStream_t stream) {
    @autoreleasepool {
    Stream* s = strata::metal::as_stream(stream);
    Tape* tape = (Tape*) exec;
    static const bool time_encoding = std::getenv("STRATA_METAL_GRAPH_TIMING") != nullptr;
    const double encode_start = time_encoding ? strata::metal::now_ns() : 0;
    if (strata::metal::kprofile_path() != nullptr && s->capturing == nullptr) {
        strata::metal::kprofile_launch(s, exec, *tape);
        return cudaSuccess;
    }
    for (const strata::metal::TapeEntry& e : tape->entries) {
        if (e.is_copy) {
            encode_copy_on(s, e.copy_dst, e.copy_dst_off, e.copy_src, e.copy_src_off, e.copy_bytes);
        } else {
            id<MTLComputeCommandEncoder> enc = strata::metal::ensure_compute(s);
            strata::metal::encode_entry(enc, e);
            if (strata::metal::encoder_per_kernel()) strata::metal::end_compute(s);
        }
    }
    if (time_encoding) {
        static std::atomic<int> index{0};
        if (index.fetch_add(1) < 32)
            std::fprintf(stderr, "metal graph: entries=%zu encode_ms=%.3f\n", tape->entries.size(),
                         (strata::metal::now_ns() - encode_start) / 1e6);
    }
    return cudaSuccess;
    }
}

cudaError_t cudaGraphUpload(cudaGraphExec_t, cudaStream_t) { return cudaSuccess; }

cudaError_t cudaGraphGetNodes(cudaGraph_t graph, cudaGraphNode_t* nodes, size_t* count) {
    Tape* tape = (Tape*) graph;
    *count = tape->entries.size();
    if (nodes != nullptr)
        for (size_t i = 0; i < tape->entries.size(); ++i) nodes[i] = (cudaGraphNode_t) (i + 1);
    return cudaSuccess;
}

cudaError_t cudaGraphNodeGetType(cudaGraphNode_t, int* type) { *type = cudaGraphNodeTypeKernel; return cudaSuccess; }

cudaError_t cudaGraphKernelNodeGetParams(cudaGraphNode_t, cudaKernelNodeParams*) {
    return fail(cudaErrorInvalidValue);                // the tape has no CUDA-style params to report
}

cudaError_t cudaGraphDestroy(cudaGraph_t graph) {
    Tape* tape = (Tape*) graph;
    for (const strata::metal::TapeEntry& e : tape->entries)
        if (e.is_copy) { [e.copy_dst release]; [e.copy_src release]; }
        // kernels' PSOs are NOT released here: the pso cache owns them for the process lifetime
    delete tape;
    return cudaSuccess;
}

cudaError_t cudaGraphExecDestroy(cudaGraphExec_t exec) {
    return cudaGraphDestroy(exec);
}

}  // extern "C"
